[package]
name = "postgres-rest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = {version = "1.0",features = ["full"]}
sqlx = {version = "0.6",features = ["postgres","runtime-tokio-rustls"]}
actix-web = "4.9.0"
serde = "1.0.218"
